### ISSUE TITLE
1.20.6 seems to be not supported

### ISSUE THREAD

**Issue by mikyvars** [Odalita-Developments/OdalitaMenus#15] opened 2024-06-23 02:05 UTC
### Describe the bug

Hello,
Previously i was on paper-1.20.4-597 and updated it for the paper-1.20.6-147 version with 0.5.6 OdalitaMenus version.
I didn't changed anything else, but my plugin have stopped working. I'm not able to interact with OdalitaMenus.

### Error examples

```
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.craftbukkit.inventory.CraftInventoryCustom$MinecraftInventory
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.1.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at Guacamole v3.0.jar/nl.odalitadevelopments.menus.nms.utils.ReflectionUtils.obcClass(ReflectionUtils.java:37) ~[Guacamole v3.0.jar:?]
	at Guacamole v3.0.jar/nl.odalitadevelopments.menus.nms.v1_20_R4.OdalitaMenusNMS_v1_20_R4.<clinit>(OdalitaMenusNMS_v1_20_R4.java:43) ~[Guacamole v3.0.jar:?]
	at Guacamole v3.0.jar/nl.odalitadevelopments.menus.OdalitaMenusImpl.initNMS(OdalitaMenusImpl.java:128) ~[Guacamole v3.0.jar:?]
	at Guacamole v3.0.jar/nl.odalitadevelopments.menus.OdalitaMenusImpl.<init>(OdalitaMenusImpl.java:96) ~[Guacamole v3.0.jar:?]
	at Guacamole v3.0.jar/nl.odalitadevelopments.menus.OdalitaMenusImpl.createInstance(OdalitaMenusImpl.java:57) ~[Guacamole v3.0.jar:?]
	at Guacamole v3.0.jar/nl.odalitadevelopments.menus.OdalitaMenus.createInstance(OdalitaMenus.java:27) ~[Guacamole v3.0.jar:?]
	at Guacamole v3.0.jar/com.michaelyvars.guacamole.game.GameManager.<init>(GameManager.java:57) ~[Guacamole v3.0.jar:?]
	at Guacamole v3.0.jar/com.michaelyvars.guacamole.Guacamole.onEnable(Guacamole.java:32) ~[Guacamole v3.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```
```
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R4/entity/CraftPlayer
	at Guacamole v3.0.jar/nl.odalitadevelopments.menus.nms.v1_20_R4.OdalitaMenusNMS_v1_20_R4.getPacketChannel(OdalitaMenusNMS_v1_20_R4.java:71) ~[Guacamole v3.0.jar:?]
	at Guacamole v3.0.jar/nl.odalitadevelopments.menus.providers.processors.packet.OdalitaPacketListenerProcessor.inject(OdalitaPacketListenerProcessor.java:78) ~[Guacamole v3.0.jar:?]
	at Guacamole v3.0.jar/nl.odalitadevelopments.menus.providers.processors.packet.OdalitaPacketListenerProcessor.onPlayerJoin(OdalitaPacketListenerProcessor.java:73) ~[Guacamole v3.0.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-147-e41d44f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R4.entity.CraftPlayer
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 27 more
```

### Minecraft version

 - Version: 1.20.6
 - Server jar: paper-1.20.6-147

**Comment by TryDev07** [comment] 2024-06-23 21:40
That's quite unusual, as version 1.20.6 should already be supported. However, I will investigate this issue further. I'm currently focused on developing the update for version 1.21, and if I discover any anomalies with version 1.20.6, I will ensure they are addressed promptly.

**Comment by Galaxy-VN** [comment] 2024-06-26 11:20
So i was asking this around paper-dev and the issue is it's not compatible with 1.20.6 Paper
this explain why ![image](https://github.com/Odalita-Developments/OdalitaMenus/assets/52485153/7283661d-7383-4cc6-a701-fdac800e010a)

**Comment by TryDev07** [comment] 2024-06-26 14:36
Ah yes I see. I will look into creating a fix for this. Thanks for the research you did.

**Comment by TryDev07** [comment] 2024-06-27 22:22
I've made an new release where this issue should be resolved. I did only test with basic menu's since our systems are still running on 1.20.1. If you're have further issues regarding this subject let me know.

**Comment by Galaxy-VN** [comment] 2024-06-28 13:23
for some reason my gradle can't found depen https://jitpack.io/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom from here hm

**Comment by TryDev07** [comment] 2024-06-30 16:28
I have released a new version on JitPack, which should resolve the dependency issue. Please let me know if the problem persists.

**Closed** 2024-07-05 05:13 UTC
Labels: bug
